import React, { useEffect, useState } from 'react';
import styles from '../styles/Home.module.css';
import Head from 'next/head';
import Link from 'next/link';

const Blog = () => {

  const [allBlog, setAllBlog] = useState([]);


  useEffect(() => {
    const getBlogData = async () => {
      try {
        const response = await fetch("http://localhost:3000/api/blog");
        const data = await response.json();
        setAllBlog(data);
      } catch (e) {
        console.log(e);
      }
    }
    getBlogData();
  }, []);

  return (
    <>
      <Head>
        <title>Hunting Coder || Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.blog}>
        <h2>Latest Blogs</h2>
        {
          allBlog?.map((curr, indx) => {
            return (
              <div className='blog-item' key={indx}>
                <Link href={`/blogpost/${curr.slug}`}>
                  <h3>{curr.title}</h3>
                  <p>{curr.content}</p>
                </Link>
              </div>
            )
          })
        }
      </div>
    </>
  )
}

export default Blog
