import React from 'react';
import styles from '../styles/Home.module.css';
import Head from 'next/head';
import Link from 'next/link';

const Blog = () => {
  return (
    <>
      <Head>
        <title>Hunting Coder || Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.blog}>
        <h2>Latest Blogs</h2>
        <div className='blog-item'>
          <Link href={"/blogpost/how-to-learn-javascript"}>
            <h3>How to learn JavaScript in 2023</h3>
            <p>JavaScript is language used to built login in website</p>
          </Link>
        </div>
        <div className='blog-item'>
        <Link href={"/blogpost/how-to-learn-python"}>
            <h3>How to learn Python in 2023</h3>
            <p>Python is language used to AI</p>
          </Link>
        </div>
        <div className='blog-item'>
          <Link href={"/blogpost/Node"}>
            <h3>How to learn Node in 2023</h3>
            <p>Node help us to built in website</p>
          </Link>
        </div>
      </div>
    </>
  )
}

export default Blog
